[[LibVPX]]
arch = "aarch64"
git-tree-sha1 = "c688e3218111a16f0364ce6a8e94e09a935494f5"
os = "macos"

    [[LibVPX.download]]
    sha256 = "ef021884c82d3db2b93264c3610f1100673668de900b2bc2a53f86cc7911ced9"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.15.2+0/LibVPX.v1.15.2.aarch64-apple-darwin.tar.gz"
[[LibVPX]]
arch = "aarch64"
git-tree-sha1 = "64966f14c2516b392b0e31a004cc712a58c7a7bd"
libc = "glibc"
os = "linux"

    [[LibVPX.download]]
    sha256 = "8c7fe6c30881f83bb08e31c26ce1006134b43c1770b032b56e8e21020f9d1049"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.15.2+0/LibVPX.v1.15.2.aarch64-linux-gnu.tar.gz"
[[LibVPX]]
arch = "aarch64"
git-tree-sha1 = "f608f380e231087397ffca728b8603981ac1c279"
libc = "musl"
os = "linux"

    [[LibVPX.download]]
    sha256 = "df6900b567a042130b59cd3cd30fd82513e681b8555f3be575b9d561bc98d8f2"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.15.2+0/LibVPX.v1.15.2.aarch64-linux-musl.tar.gz"
[[LibVPX]]
arch = "aarch64"
git-tree-sha1 = "c0f714274afacbde3e28c9862ed20ef166178f6e"
os = "freebsd"

    [[LibVPX.download]]
    sha256 = "5e184a6433dcd7d45ff48610d3359a70de3635b3f1c6f2b51376d0efe7d1e1b4"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.15.2+0/LibVPX.v1.15.2.aarch64-unknown-freebsd.tar.gz"
[[LibVPX]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4497336ef2d13472e7f1abfb4ec73f26ebea8daf"
libc = "glibc"
os = "linux"

    [[LibVPX.download]]
    sha256 = "ab649c3f2a8352975f300e75ba86695ec56cacfde10b5d2d4aa921fb44c0cdf5"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.15.2+0/LibVPX.v1.15.2.armv6l-linux-gnueabihf.tar.gz"
[[LibVPX]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4ed11bfa34a3317e412904fc5d24e36423533368"
libc = "musl"
os = "linux"

    [[LibVPX.download]]
    sha256 = "34488e8331a229822c0c0bc5ee1ab3fb6e16b7f2636e0e27f25c28e2e2aa5e99"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.15.2+0/LibVPX.v1.15.2.armv6l-linux-musleabihf.tar.gz"
[[LibVPX]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a510b67be3285b50a84e246400d30936b24d058a"
libc = "glibc"
os = "linux"

    [[LibVPX.download]]
    sha256 = "bd0dad18e0c1c327b65bc48e5cd0eef2aea237398a8e72f577a8dffec5c5ca5b"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.15.2+0/LibVPX.v1.15.2.armv7l-linux-gnueabihf.tar.gz"
[[LibVPX]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fd29c4f1326b7aa1df9aad2f6542302e82bace6e"
libc = "musl"
os = "linux"

    [[LibVPX.download]]
    sha256 = "8e743973fce3a1520d7b13379368361dcfcc7559c4becd741f58ddc48e25f7c4"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.15.2+0/LibVPX.v1.15.2.armv7l-linux-musleabihf.tar.gz"
[[LibVPX]]
arch = "i686"
git-tree-sha1 = "32ed9d25b1b5038f7c1151250b292715dca23ba8"
libc = "glibc"
os = "linux"

    [[LibVPX.download]]
    sha256 = "dd38a44514a751a6c87319da43a2e6ac85981339dced182b669e1cc67eae778a"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.15.2+0/LibVPX.v1.15.2.i686-linux-gnu.tar.gz"
[[LibVPX]]
arch = "i686"
git-tree-sha1 = "8ea39a61702e375ecfd3b5b9ebec74dcffd2d87a"
libc = "musl"
os = "linux"

    [[LibVPX.download]]
    sha256 = "d4bf7e5ac1f748ff21eaea2477390789500248c5eb4af9a9bcd5ab95def59fa3"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.15.2+0/LibVPX.v1.15.2.i686-linux-musl.tar.gz"
[[LibVPX]]
arch = "i686"
git-tree-sha1 = "8832d59bf6ca6d636c473f1b5ed4f9eeb39455e5"
os = "windows"

    [[LibVPX.download]]
    sha256 = "ea71baeea6dd99c4c45dbff9bc2beab43d88a6a9df73686674608a76fc0bcfb8"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.15.2+0/LibVPX.v1.15.2.i686-w64-mingw32.tar.gz"
[[LibVPX]]
arch = "powerpc64le"
git-tree-sha1 = "ffe33a9e39da7185f6d7e2cf4dcb0c3644b5bd57"
libc = "glibc"
os = "linux"

    [[LibVPX.download]]
    sha256 = "3346bd5f405f3c48c0513c145bcb5585327a35a49d84a4fb510f80310cefe7ac"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.15.2+0/LibVPX.v1.15.2.powerpc64le-linux-gnu.tar.gz"
[[LibVPX]]
arch = "riscv64"
git-tree-sha1 = "fbfb4bf91ce985de2efa883c9c3d221a86946448"
libc = "glibc"
os = "linux"

    [[LibVPX.download]]
    sha256 = "10b3f231e620696974e25dbded5a609bc1fb87f3ce235d6b752603b07df9f240"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.15.2+0/LibVPX.v1.15.2.riscv64-linux-gnu.tar.gz"
[[LibVPX]]
arch = "x86_64"
git-tree-sha1 = "2c7d21d043e239c971b62a0bd23f9c0bc50aff7a"
os = "macos"

    [[LibVPX.download]]
    sha256 = "fbb26ad94b0cd97c6dcb99343e8272b5537807204988648df26ed4d563d1c497"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.15.2+0/LibVPX.v1.15.2.x86_64-apple-darwin.tar.gz"
[[LibVPX]]
arch = "x86_64"
git-tree-sha1 = "262cd3355cecd2aa8e3e41e44341dec8e240c30b"
libc = "glibc"
os = "linux"

    [[LibVPX.download]]
    sha256 = "60816164da8adceaae0ab1c59b65abe448ca71545c01fb7c54c551cdd6a485bb"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.15.2+0/LibVPX.v1.15.2.x86_64-linux-gnu.tar.gz"
[[LibVPX]]
arch = "x86_64"
git-tree-sha1 = "83f2ba31be0b003a35ab46e1202e73ff2dbc471f"
libc = "musl"
os = "linux"

    [[LibVPX.download]]
    sha256 = "7c443e1110195f7aefe4bf4891a39a65c7c63b3165ee057294f232b1db6cf15e"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.15.2+0/LibVPX.v1.15.2.x86_64-linux-musl.tar.gz"
[[LibVPX]]
arch = "x86_64"
git-tree-sha1 = "779654d3a29189c41a74e32df1b6c069f3a79f8e"
os = "freebsd"

    [[LibVPX.download]]
    sha256 = "91f8e8b260ff3aa2a12c6a5f20ffb8012b291b90756c53838510af4efa695192"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.15.2+0/LibVPX.v1.15.2.x86_64-unknown-freebsd.tar.gz"
[[LibVPX]]
arch = "x86_64"
git-tree-sha1 = "5798ee1a181e4f22d8f39488449d416eb0771a2d"
os = "windows"

    [[LibVPX.download]]
    sha256 = "a696854076d16d795cd943c5b31a9c79d86fd6c6350a1e7a7a5cd788a36b5c97"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.15.2+0/LibVPX.v1.15.2.x86_64-w64-mingw32.tar.gz"
