[[LibVPX]]
arch = "armv7l"
git-tree-sha1 = "acad6db62ef5197687ff37e878e58494d219459f"
libc = "musl"
os = "linux"

    [[LibVPX.download]]
    sha256 = "c8084bc8ad7e8c0fa16b02f24141737912919692629b0356e0d21d4f816d6b7a"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.8.1+0/LibVPX.v1.8.1.arm-linux-musleabihf.tar.gz"
[[LibVPX]]
arch = "powerpc64le"
git-tree-sha1 = "b1651d72da104b856d77d96fd4b6e04841f853ba"
libc = "glibc"
os = "linux"

    [[LibVPX.download]]
    sha256 = "8487907b286ae9f79653b5ac5efbf4123e6eeecc8e74841bf413d3fc44c1d865"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.8.1+0/LibVPX.v1.8.1.powerpc64le-linux-gnu.tar.gz"
[[LibVPX]]
arch = "x86_64"
git-tree-sha1 = "cbf1f858c4b8c0ce28a2ebd2e4485bae302042d8"
os = "macos"

    [[LibVPX.download]]
    sha256 = "40373364c23aa5261c9a2e73ccee6b8af4bc6466c8ab5575d212b849c2011695"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.8.1+0/LibVPX.v1.8.1.x86_64-apple-darwin14.tar.gz"
[[LibVPX]]
arch = "aarch64"
git-tree-sha1 = "86d24b30f033f5453900d386ae3f400a7265c964"
libc = "glibc"
os = "linux"

    [[LibVPX.download]]
    sha256 = "9440fcdf172b9696843acf6c5294c93e2a40cbb7efbf53046fa3ad09255c40e6"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.8.1+0/LibVPX.v1.8.1.aarch64-linux-gnu.tar.gz"
[[LibVPX]]
arch = "armv7l"
git-tree-sha1 = "f9939a54ea7c26d44329a3300d431605cc20eb28"
libc = "glibc"
os = "linux"

    [[LibVPX.download]]
    sha256 = "98b775eff3ad14daa01436a728f11cd26da9e25c6b27af5bd823a33ad57d4c86"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.8.1+0/LibVPX.v1.8.1.arm-linux-gnueabihf.tar.gz"
[[LibVPX]]
arch = "i686"
git-tree-sha1 = "0a6fe4753f42cac95e42e08181066b8e671a6446"
libc = "musl"
os = "linux"

    [[LibVPX.download]]
    sha256 = "df648f3e4fb139344529f4a21bb2d5ba6becbdaf2545b7d0d5ff154f6a00d34c"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.8.1+0/LibVPX.v1.8.1.i686-linux-musl.tar.gz"
[[LibVPX]]
arch = "x86_64"
git-tree-sha1 = "15f9ae361701a964e6c42206513d6593333ac149"
libc = "glibc"
os = "linux"

    [[LibVPX.download]]
    sha256 = "e480c242256d2132fafce0e53c251e9be9e11629a356258169158de8e25e8b0f"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.8.1+0/LibVPX.v1.8.1.x86_64-linux-gnu.tar.gz"
[[LibVPX]]
arch = "x86_64"
git-tree-sha1 = "45606d1690fa36c525eaa94d60f58e4185236303"
os = "windows"

    [[LibVPX.download]]
    sha256 = "37b1a43e31bf1f015d254ebba3587d5f9612768945c5529a512a4c20b262c001"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.8.1+0/LibVPX.v1.8.1.x86_64-w64-mingw32.tar.gz"
[[LibVPX]]
arch = "aarch64"
git-tree-sha1 = "89da9e8adc3653ea44dbfe16e8261a9e9581af7b"
libc = "musl"
os = "linux"

    [[LibVPX.download]]
    sha256 = "46596ea6bf0eac1bdb4bd74cc1ee3f65db6ab56d05f21c4d834bdae6025b89de"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.8.1+0/LibVPX.v1.8.1.aarch64-linux-musl.tar.gz"
[[LibVPX]]
arch = "i686"
git-tree-sha1 = "2bf17df567ca43752b6aa03699c872b04b386444"
libc = "glibc"
os = "linux"

    [[LibVPX.download]]
    sha256 = "8d070d2d17666a7a3866862a79459ebb5f831b2d685938546600224289991ed7"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.8.1+0/LibVPX.v1.8.1.i686-linux-gnu.tar.gz"
[[LibVPX]]
arch = "x86_64"
git-tree-sha1 = "de551bc3d88926aa8e816439c867b83d97899801"
libc = "musl"
os = "linux"

    [[LibVPX.download]]
    sha256 = "4067eb5fecaa1ffa0cd2f2945431d0b6aa5025dbb3c46b838884cf61007d1986"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.8.1+0/LibVPX.v1.8.1.x86_64-linux-musl.tar.gz"
[[LibVPX]]
arch = "x86_64"
git-tree-sha1 = "fbaccecb9a94025c0abe9b3137933f6a9d90c3d6"
os = "freebsd"

    [[LibVPX.download]]
    sha256 = "13c4df505db7d611bc823ae1c81b295bfeb8b9d531a48b7dca49c650969a12d6"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.8.1+0/LibVPX.v1.8.1.x86_64-unknown-freebsd11.1.tar.gz"
[[LibVPX]]
arch = "i686"
git-tree-sha1 = "103066696246a604470571de134fe05b1199994d"
os = "windows"

    [[LibVPX.download]]
    sha256 = "cdfc859ed8942e413ef4be0807b6534a9b396b76deced62c162328fefb4c605f"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.8.1+0/LibVPX.v1.8.1.i686-w64-mingw32.tar.gz"
