[[LibVPX]]
arch = "aarch64"
git-tree-sha1 = "c245a1d9e0dc88999f6e26d29412f8a303582517"
os = "macos"

    [[LibVPX.download]]
    sha256 = "ffd7bed562aaf07825e1de7d9b9dae6742354833b680b31dbe36ecda42e847c0"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.10.0+0/LibVPX.v1.10.0.aarch64-apple-darwin.tar.gz"
[[LibVPX]]
arch = "aarch64"
git-tree-sha1 = "ec6148a1ef5ccb0f23e9aaf5a68a521e3093f674"
libc = "glibc"
os = "linux"

    [[LibVPX.download]]
    sha256 = "67fa173155ffb93245353329ec44bd0d54d727f349d012d5205cfe5ba2786191"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.10.0+0/LibVPX.v1.10.0.aarch64-linux-gnu.tar.gz"
[[LibVPX]]
arch = "aarch64"
git-tree-sha1 = "13572ac430dbf1686e674b53cdac15e2c4cb9278"
libc = "musl"
os = "linux"

    [[LibVPX.download]]
    sha256 = "787b86045b132814c2035a8ac3250df1eadb90e978cfb7a46c75a1b4614ee019"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.10.0+0/LibVPX.v1.10.0.aarch64-linux-musl.tar.gz"
[[LibVPX]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ccb1464a9d3c0f312ed0fb48f812526d4a1aaed9"
libc = "glibc"
os = "linux"

    [[LibVPX.download]]
    sha256 = "b22155b079dd3669340e9bfab2a3c7f5d96496607358b97f901963dfae8c4600"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.10.0+0/LibVPX.v1.10.0.armv7l-linux-gnueabihf.tar.gz"
[[LibVPX]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "68c1e8b8f7b808e2b67e85d6a2423bc3dfc633a4"
libc = "musl"
os = "linux"

    [[LibVPX.download]]
    sha256 = "6c99b0f1ce156647549b279d7dd2591d161601befca8838dab9d9cde6ce8daf9"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.10.0+0/LibVPX.v1.10.0.armv7l-linux-musleabihf.tar.gz"
[[LibVPX]]
arch = "i686"
git-tree-sha1 = "addd623072bde32df04b96b2723d465a0f5a48e9"
libc = "glibc"
os = "linux"

    [[LibVPX.download]]
    sha256 = "ece73da0465054641f1f9ccfefc890b7618f7ac1b963a0499fd16fa5634c7371"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.10.0+0/LibVPX.v1.10.0.i686-linux-gnu.tar.gz"
[[LibVPX]]
arch = "i686"
git-tree-sha1 = "b639b111b7040f4d764b2fe481c65c38a18eb2e7"
libc = "musl"
os = "linux"

    [[LibVPX.download]]
    sha256 = "33d6bf6d3e7c2d85c0a13d75166eedbaca0dbd96bdfa0c240f0dc1bfa194a7a3"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.10.0+0/LibVPX.v1.10.0.i686-linux-musl.tar.gz"
[[LibVPX]]
arch = "i686"
git-tree-sha1 = "40abb6745ed9b8fa870d650305a9d0de0c2d5990"
os = "windows"

    [[LibVPX.download]]
    sha256 = "56fbce01af816977d9878755c5cbf2ad58fea35ad6f7b33965e5fc143a170006"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.10.0+0/LibVPX.v1.10.0.i686-w64-mingw32.tar.gz"
[[LibVPX]]
arch = "powerpc64le"
git-tree-sha1 = "9cf615aa707eb37b1543241e535b2ebb46a220e2"
libc = "glibc"
os = "linux"

    [[LibVPX.download]]
    sha256 = "b162bdaf24df14854bf4c8f4f6f4117cdadff8f03976884360d5b4daf923d97e"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.10.0+0/LibVPX.v1.10.0.powerpc64le-linux-gnu.tar.gz"
[[LibVPX]]
arch = "x86_64"
git-tree-sha1 = "4c01ae4a2f23fb47f6640249245e3bcd95e1d60d"
os = "macos"

    [[LibVPX.download]]
    sha256 = "9c7c7a38299f252e2d8135df5df16a65a73cfff10a815f6ef69f08726650bbe4"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.10.0+0/LibVPX.v1.10.0.x86_64-apple-darwin.tar.gz"
[[LibVPX]]
arch = "x86_64"
git-tree-sha1 = "f3c224dfc71a38eeee0c39fb1db9056160ec34c2"
libc = "glibc"
os = "linux"

    [[LibVPX.download]]
    sha256 = "f6156c1ec21244703be2818d9308ad390d596ee4bf182cddaf791db1f04f5a15"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.10.0+0/LibVPX.v1.10.0.x86_64-linux-gnu.tar.gz"
[[LibVPX]]
arch = "x86_64"
git-tree-sha1 = "75e2d3e6915e939a3d1a1c369bce13a300e7d2ae"
libc = "musl"
os = "linux"

    [[LibVPX.download]]
    sha256 = "d91ffdf8814b0ad34127965c87785fc8b571f77fbb562da7c475a7305468979b"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.10.0+0/LibVPX.v1.10.0.x86_64-linux-musl.tar.gz"
[[LibVPX]]
arch = "x86_64"
git-tree-sha1 = "8f8a80cc03c55c8359cfd75129c4c232a04e2567"
os = "freebsd"

    [[LibVPX.download]]
    sha256 = "5a595fe79ba2adfead24897170856c9da5219c38e5a8dc2b6437731bc59d6782"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.10.0+0/LibVPX.v1.10.0.x86_64-unknown-freebsd.tar.gz"
[[LibVPX]]
arch = "x86_64"
git-tree-sha1 = "d3730fed8bead6fd12d45b28f0690c5915917a79"
os = "windows"

    [[LibVPX.download]]
    sha256 = "7724b91e73c3a3df46df8a2cf663eb1873d27ff98bffbd12938c2a53e02b4f54"
    url = "https://github.com/JuliaBinaryWrappers/LibVPX_jll.jl/releases/download/LibVPX-v1.10.0+0/LibVPX.v1.10.0.x86_64-w64-mingw32.tar.gz"
