# Autogenerated wrapper script for LibVPX_jll for i686-w64-mingw32
export libvpx

## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "PATH"
LIBPATH_default = ""

# Relative path to `libvpx`
const libvpx_splitpath = ["bin", "libvpx.a"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libvpx_path = ""

# libvpx-specific global declaration
# This will be filled out by __init__()
libvpx = ""


"""
Open all libraries
"""
function __init__()
    global artifact_dir = abspath(artifact"LibVPX")

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    global libvpx_path = normpath(joinpath(artifact_dir, libvpx_splitpath...))

    global libvpx = libvpx_path
    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ';')
    global LIBPATH = join(vcat(LIBPATH_list, [Sys.BINDIR, joinpath(Sys.BINDIR, Base.LIBDIR, "julia"), joinpath(Sys.BINDIR, Base.LIBDIR)]), ';')

    
end  # __init__()

